# Generated by Django 4.2.1 on 2023-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_e', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phonenumber',
            field=models.CharField(blank=True, default=1, max_length=18, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
